### ISSUE TITLE
initial package structure

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#1]
We should add initial package structure similarly to other repositories. (e.g. see recently added `r-w-commons`)

Even though this will be basically a JS frontend project, I think it will be good to keep the documentation in reST and Sphinx and publish it on RTFD for the harmony with the other REANA ecosystem components.

**Comment by diegodelemos** [comment]
Closed by https://github.com/reanahub/reana-ui/commit/4d7c815b5bf4972d54ee91c1c47646ef138a8b52.
