### ISSUE TITLE
implementation: workflow-list

### ISSUE THREAD

**Issue by Sinclert** [reanahub/reana-ui#10]
Starting workflow-list implementation

**Comment by Sinclert** [comment]
We thought it was interesting to introduced a new column (not showed in the mockups), which is the `duration` of the executions. I was thinking about following the format `HH h MM m SS s`.

Example: 
![screen shot 2018-07-24 at 13 56 12](https://user-images.githubusercontent.com/6978377/43136540-595f832e-8f49-11e8-859e-6eae302c72e0.png)

**Comment by dinosk** [comment]
:+1: the duration column looks great
