### ISSUE TITLE
your settings: order of icons

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#105]
A feature to hide token was recently introduced.  This leads to UI showing:

![2020-06-16-142506_740x233_scrot](https://user-images.githubusercontent.com/517546/84773887-57916100-afdd-11ea-9425-f2803d81d037.png)

It may be perhaps more natural to invert the order of top-right icons: first you want to view the content, and only then you want to copy it into the clipboard?

**Comment by mvidalgarcia** [comment]
It's been addressed [here](https://github.com/reanahub/reana-ui/pull/104/commits/c159c10f65229fcdad1ed2451d4cd6fb264d9c0d). I'll tag the commit.
