### ISSUE TITLE
workflow: page refresh showing two intermediate pages 

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#106]
When users are viewing a detailed workflow page, they have a possibility to refresh/reload the page to see the latest progress status, for example via icon:

![2020-06-16-142942_268x76_scrot](https://user-images.githubusercontent.com/517546/84774404-12b9fa00-afde-11ea-8183-4cc06c870416.png)

However, reloading the page has the following effect:

- the original detailed workflow page disappears;
- a first intermediate page, all white, with the text "Loading..." is shown;
- a second intermediate page, all black, with the text "Loading workflow..." is shown;
- the refreshed detailed workflow page is shown.

This is not ideal, because the old information is gone, and the two intermediate pages lead to flashing reverse video, which is disturbing on the eyes.

This may last for sometimes up to 5 seconds, so it is very visible.

Ideally, we should (i) not change white/black background of the intermediate loading pages; (ii) show only one of them, styled very gently; or (iii) still show the old content as much as possible, so that users have something to look at, before the new content is being ready for display.

Could we improve this refresh-workflow-page behaviour?

**Comment by mvidalgarcia** [comment]
We can make both loading pages white to prevent the blinking effect.
This reload button was a workaround to point out that the information displayed is not automatically updated. Eventually, when we get rid of polling and implement [websockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications), the reload won't be needed at all.

**Comment by mvidalgarcia** [comment]
The blinking effect was already fixed in https://github.com/mvidalgarcia/reana-ui/commit/1009437274917728a92f07309bd0eb7c41baba12, now all the loading pages have the same background color.
