### ISSUE TITLE
single-user deployment: 404 page not found

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#114]
Trying 0.7.0-alpha.1 is a single-user deployment mode:

```console
$ reana-dev run-ci -m /var/reana:/var/reana --exclude-components=r-a-vomsproxy,r-a-krb5 -c r-d-helloworld
```

leads to working platform except for the home page:

```console
$ wget --no-check-certificate https://0.0.0.0:30443
...
HTTP request sent, awaiting response... 404 Not Found
2020-08-31 09:32:49 ERROR 404: Not Found.
```

**Comment by mvidalgarcia** [comment]
With the defaults we have in [`values.yaml`](https://github.com/reanahub/reana/blob/master/helm/reana/values.yaml#L51), the [UI pod is not even created](https://github.com/reanahub/reana/blob/master/helm/reana/templates/reana-ui.yaml#L1), that's likely the reason why you can't access it.

IIRC in the pre-kind era we had this logic inverted, UI was enabled by default and one had to pass `EXCLUDE_COMPONENTS=r-ui` to `make deploy` to exclude it.

**Comment by tiborsimko** [comment]
If the UX for local-user-db deployment scenarios is nice, we can enable it by default. (E.g. the person installing REANA should know which username and which password to use when logging to the UI...)

Otherwise for make vs kind, we have a possibility to store several Helm configuration options such as `helm/configurations/values-dev.yaml` so we could create `values-dev-ui.yaml`, `values-dev-no-ui.yaml` etc for each scenario, and based on `--exclude-components` option the `reana-dev` could use appropriate values file when bringing up the cluster.

Suggestions:
- let's enable UI by default; good for people installing REANA via Helm directly;
- let's improve UX for the installer WRT login/password/token later as part of another ticket;
