### ISSUE TITLE
quotas: allow users to recover quota

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-ui#129]
- Provide `reana-client` instructions on how to delete workflow runs (MVP)
- Offer buttons to delete workflow runs
- Show quota consumption per workflow

**Comment by tiborsimko** [comment]
The first using R/O approach to Web UI, the second starting to use R/W approach for the first time...

**Comment by mvidalgarcia** [comment]
Related UI mockup with delete buttons. We should display a modal asking for confirmation and warning the user that workflow will be not recoverable.

![image](https://user-images.githubusercontent.com/8863238/94414324-8098c480-017c-11eb-82d6-e069c0452384.png)

**Comment by mvidalgarcia** [comment]
> Provide `reana-client` instructions on how to delete workflow runs (MVP)

Isn't this equivalent to `reana-client delete -w my_workflow --include-records`?
