### ISSUE TITLE
build: optimize the build size

### ISSUE THREAD

**Issue by audrium** [reanahub/reana-ui#135]
- It seems that we are importing the whole `lodash` library. Instead of `import _ from "lodash";` we could import it like this: `import has from 'lodash/has';`. [Link](https://selleo.com/til/posts/0ac258eyv8-decrease-bundle-size-by-importing-lodash-correctly)
- Similarly we could investigate if it's possible to save some bundle size by optimizing `moment.js` 

Source map:
![bundle](https://user-images.githubusercontent.com/4990025/94656377-4f490180-0300-11eb-9960-34752b50b278.png)

**Comment by mvidalgarcia** [comment]
Some notes:
- All the `lodash` imports have been replaced with the specific function import to save bundle size.
- `moment.js` is _kind of_ deprecated. Even they [recommend](https://momentjs.com/docs/#/-project-status/) using other alternatives on https://momentjs.com.

  > Considering using Moment in your project?
There may be better modern alternatives.
For more details and recommendations,
please see [Project Status](https://momentjs.com/docs/#/-project-status/) in the docs.

  They now maintain the [Luxon](https://moment.github.io/luxon/#/) library which is [lighter](https://bundlephobia.com/package/luxon@2.3.1). Another alternative would be waiting for the [`Temporal`](https://tc39.es/proposal-temporal/docs/index.html) standard API to be published, which is now on stage 3.


For reference, here's the current source map, looks like we improved a bit :)

<img width="1782" alt="image" src="https://user-images.githubusercontent.com/8863238/157694052-4ab72a1b-80f2-46fe-b825-c3924659d26e.png">
