### ISSUE TITLE
docs: missing developer guide

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-ui#150]
While moving to docs.reana.io, we [removed](https://github.com/reanahub/reana-ui/commit/b9ce1cf1b9fcffcd1fcf00a2a35007810092748a) the [R-UI developer guide](https://github.com/reanahub/reana-ui/blob/1652d4ae468665be26faf712b0aad37096955632/docs/developerguide.rst). These are valuable instructions when trying to reproduce problems related to login in production/QA. Shall we:
- 🚀   Put it back in the [read the docs](https://reana-ui.readthedocs.io/en/latest/)
- 🎉   Move it to the [reanahub/reana's wiki](https://github.com/reanahub/reana/wiki)

Other options?

**Comment by mdonadoni** [comment]
GitLab integration was already added to `reana` wiki: https://github.com/reanahub/reana/wiki/Tips-for-GitLab#configure-gitlab-integration-locally
Quick start guide/Prettier are already part of the README.
