### ISSUE TITLE
ui: display workflow size in workflow details page

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-ui#152]
Also, not necessarily belonging to this PR, but we should display the size on the details page as well, we're not doing it at the moment. This comment can be converted into an issue if you find this appropriate.

_Originally posted by @mvidalgarcia in https://github.com/reanahub/reana-ui/pull/146#discussion_r513528984_

**Comment by mvidalgarcia** [comment]
Duplication of https://github.com/reanahub/reana-ui/issues/151
