### ISSUE TITLE
ui: refine workflow logs

### ISSUE THREAD

**Issue by alintulu** [reanahub/reana-ui#166]
If the workflow fails at the workflow engine level, before starting any jobs, the UI shows no error logs. While you can get the complete logs with the client, it might be confusing for some users to see a failed workflow without any errors on the UI. 

Possible solutions

*  Show only the workflow engine logs if the workflow fails before creating jobs
* Add another tab (e.g. next to "Step") or option in drop down to show workflow  engine logs. Could be always present.

**Comment by mvidalgarcia** [comment]
With the [allowing users to specify memory limits per job feature](https://github.com/reanahub/reana-client/issues/496), users will get a workflow engine level log when exceeding the memory limits.

```console
reana-client logs -w test-memory-limit                                                       
==> Workflow engine logs                                       
Workflow exited unexpectedly.                                  
Job submission error: The "kubernetes_memory_limit" provided (10.1Gi) exceeds the limit (10Gi).             
```

This is not visible in the UI and there's no info displayed.

![image](https://user-images.githubusercontent.com/8863238/116576312-bcad2700-a90f-11eb-827f-3845805fdbf7.png)


Bumping priority then! ⬆️

**Comment by lukasheinrich** [comment]
I think it would be great to have a way to generally view engine logs in the UI
