### ISSUE TITLE
implementation: config.js file

### ISSUE THREAD

**Issue by Sinclert** [reanahub/reana-ui#17]
In order to stored general and common variables names, such as the endpoints URLs, or the table pooling interval seconds, we were thinking about creating a `config.js` with all those variables inside.

Any regards on this?

**Comment by Sinclert** [comment]
Done #18

**Comment by diegodelemos** [comment]
Lets leave the work of closing the issue to GitHub once we have the specific commit implementing configuration merged, adding the [closes statement](https://help.github.com/articles/closing-issues-using-keywords/) in the commit message in #18 !

**Comment by Sinclert** [comment]
Closed #18
