### ISSUE TITLE
footer: missing Mattermost chat link and RoPO position

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#180]
At CERN deployment, the Mattermost chat link is missing in the footer:

![chat](https://user-images.githubusercontent.com/517546/110766138-28024300-8255-11eb-81fd-1d7bd620428b.png)

This can be amended via Helm deployment values regarding chat URL, but it also raises a question that it may be perhaps more appropriate to move the RoPO link next to copyright (see also #178), so that the left-hand-side footer section will become a "legal corner"  (displaying only copyright and privacy notice link), and the right-hand side footer section will become "user help" corner (displaying chat, forum and docs links).

**Comment by mvidalgarcia** [comment]
GitLab MR for QA and PROD: https://gitlab.cern.ch/reanahub/deployment/-/merge_requests/36
