### ISSUE TITLE
ui: prototype new page to show users REANA cluster status

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-ui#183]
In the context of the [Big multi-user workflows](https://github.com/orgs/reanahub/projects/37) sprint, we will come up with more dynamic ways of deciding whether a workflow should be started or not.

This will make users wonder why their workflows take long to be queued. This new page is intended to give users information about whether the cluster is busy, so they can relate to why their workflows take long to be scheduled.

Steps:
- Serve information to the UI (information should be provided by https://github.com/reanahub/reana/issues/501)
  - Node health: percentage of nodes up (unschedulable vs total). Pie chart.
  - Workflow health: percentage of running vs pending/queued workflows. Pie chart.
  - Job health: percentage of running vs pending/queued jobs. Pie chart.
- Mockup the new page
  - To take inspiration from other systems such as Pachyderm, Kubeflow etc...
- Implement mockup and connect to backend

Note:
- We already have a [`status.py` in RS](https://github.com/reanahub/reana-server/blob/master/reana_server/status.py) which could be extended for this case
- This should be easily extensible since new measures can come up while progressing in other tasks in the sprint.

**Comment by mvidalgarcia** [comment]
**1st mockup iteration.**

![image](https://user-images.githubusercontent.com/8863238/117482928-5fdfeb00-af65-11eb-9ea8-fcd4407983af.png)
