### ISSUE TITLE
api: switch fetch for axios to make rest calls

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-ui#19]
Shall we switch from `fetch` to `axios`? For better error handling and more user friendliness. 

See article listing the reasons [here](https://medium.com/@thejasonfile/fetch-vs-axios-js-for-making-http-requests-2b261cdd3af5).

**Comment by Sinclert** [comment]
Done ✅

**Comment by Sinclert** [comment]
Closed #18
