### ISSUE TITLE
state: introduce Redux to manage application state

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-ui#20]
Use [Redux](https://redux.js.org/) to manage application state.

References:
[Analysis Preservation UI source code](https://github.com/cernanalysispreservation/analysispreservation.cern.ch/tree/master/ui/src)
[Redux Discord chat](https://discord.gg/0ZcbPKXt5bZ6au5t)

**Comment by Sinclert** [comment]
It is also important to keep the `token` in local storage (cookie), that way any page reload can check if the login has been properly done or not.

We could use [Universal-cookie](https://github.com/reactivestack/cookies/tree/master/packages/universal-cookie) or [Redux-persist](https://github.com/rt2zz/redux-persist), if we finally choose to go for Redux.

**Comment by diegodelemos** [comment]
Closed by https://github.com/reanahub/reana-ui/pull/41.
