### ISSUE TITLE
docker: add initial Dockerfile which can be run and serve the UI   

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-ui#21]
As a result we will have a Docker image which can be configured (configuration part depends on https://github.com/reanahub/reana-ui/issues/17) to connect to any REANA Server.

We should give preference to configuration through environment variables  (see how it is done for example in REANA Server [here](https://github.com/reanahub/reana-server/blob/master/reana_server/config.py#L29-L30)) since we are following the [12factor methodology](https://12factor.net). If not possible, we could provide the file using volume mounts with plain Docker and [ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) when inside Kubernetes.

**Comment by David-Development** [comment]
What is the current progress on this? Is there a way to test the reana-ui yet? It looks like that the UI is based on react, is that correct? A couple of month ago I created a [Dockerfile](https://github.com/David-Development/heimdall-frontend/blob/master/Dockerfile) for another react project I was working on. Basically the following should do the trick:

```Dockerfile
# https://hub.docker.com/_/node/
FROM node:9-alpine

RUN npm install -g yarn serve
WORKDIR /app/
COPY package.json yarn.lock ./
COPY . /app

RUN yarn install --frozen-lockfile --no-cache --production && \
    yarn build && \
    rm -R node_modules; \

CMD serve -s build --port 3000
```

I'm evaluating different workflow-engines as part of my master thesis - reana is one of them. However for our use-case we need a UI.

**Comment by tiborsimko** [comment]
@David-Development The work on REANA-UI is "paused", as it were.  We are now improving the workflow commands for the live workflow development and interaction (such as stop, resume, etc) as part of the [Live-Mode](https://github.com/reanahub/reana/issues/109) sprint. This will be followed by another sprint on improving logging in the platform. We shall resume working on REANA UI afterwards when we shall also plug into the UI all this newly developed end-user functionality.  (Probably around Dec2018/Jan2019.)

**Comment by David-Development** [comment]
@tiborsimko Oh okay, I see. Thank you for the status update! Looking forward to test the UI. (I'll be actively testing frameworks / workflow-engines until mid January 2019).

**Comment by diegodelemos** [comment]
Closed by https://github.com/reanahub/reana/pull/186, https://github.com/reanahub/reana-ui/pull/30 and https://github.com/reanahub/reana-cluster/pull/217.
