### ISSUE TITLE
workflow list: provide option to hide deleted workflows

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#218]
**Current behaviour**

The workflow list page allows filtering workflows by status:

![filter](https://user-images.githubusercontent.com/517546/154315106-9b960b6c-3568-473b-ad84-cb62e9f65717.png)

However, this filtering does not allow to _hide_ some workflows, such as deleted workflows, by default.

**Expected behaviour**

It would be useful to offer an option to users not to see deleted workflows. This could be implemented (i) on the workflow list page via some UI element such as checkbox saying `[x] hide deleted workflows`, but perhaps (ii) even better would be to offer personalised global user settings option that people could set in their "Your profile" / "Your setting" pages. (Alongside with other interesting configurable options, such as the number of hits to display per page, in the longer-term future.)

**Comment by mvidalgarcia** [comment]
In my opinion, (i) or a similar approach is better discoverable than (ii). I think that the options that affect directly the items displayed should be grouped.

As a user, I wouldn't expect to go to my profile to tweak a global option that affects the list of workflows displayed on the home page, and even more knowing that there are already some filters on the workflows list.

**Comment by mdonadoni** [comment]
For now, I think it would be a good idea to implement option (i). The user choice to show/hide deleted workflows would not be persisted, but it would be reset just like the filtering by status or by name that are already present in REANA UI. 

If in the future we want this choice to be saved in REANA's database, possibly along with other user customizations, we can then switch to option (ii), either maintaining or not (i).

What do you think?
