### ISSUE TITLE
launcher: prettify landing page

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#231]
Consider a custom badge launching RooFit demo with different number of events and different file name of output plot:

https://0.0.0.0:30443/launch?url=https://github.com/reanahub/reana-demo-root6-roofit.git&name=test&parameters={"events":1000,"plot":"results/myplot.png"}

The current launcher web page looks like:

![launch-nice-ui](https://user-images.githubusercontent.com/517546/157421580-1b5e42ea-8c30-4fb2-91bd-8a123b3f03fc.png)

We can prettify it a bit, e.g. put human-oriented language and display parameters separately, perhaps like:

```
Launch on REANA

* Workflow name: test
* Workflow specification: https://github... (and link back to external source)
* Workflow parameters:
    - events: 1000
    - plot: results/myplot.png

 [LAUNCH]
```

An MVP would be to created something visually attractive along these lines.

A Beyond-MVP would be to think about allowing some of the above text areas as editable. This would go towards the future possibility to _modify_ values passed by the badge as a sort of poor-man's slider. E.g. badge says 1000 events, but the user would like to launch a workflow generating 100000 events. The intermediate launcher page could allow this if we extend it to modify recognised URL parameters.

**Comment by mvidalgarcia** [comment]
Some quick mockups:

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/8863238/157862060-7da155c2-c541-4815-92b3-64e1f5674cd8.png">

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/8863238/157862797-a3dedd18-38a4-4c88-b89c-54a68230b348.png">


I tried to follow the same design lines as the workflow list, but the final result is not very convincing to me as it might cause some confusion. I would like to hear some opinions and suggestions :)

**Comment by audrium** [comment]
Looks nice, I personally like the first one. But I see what you mean that users could think it's a workflow list page..
One observation is that we shouldn't rely on the workflow name so much, since it's optional parameter. I guess without the name it looks a bit more empty? In that case `Launch` button perhaps be better suited bellow the text to fill up some space?

**Comment by mvidalgarcia** [comment]
> One observation is that we shouldn't rely on the workflow name so much, since it's optional parameter. I guess without the name it looks a bit more empty?

I guess that for this case we can display the workflow name generated by the backend, but this would require an additional connection to the server.

**Comment by tiborsimko** [comment]
Some comments:

- I like the idea of having close analogy with the workflow list item. One suggestion to make the analogy even more apparent: what about including some leading icon in front of the workflow name -- perhaps grayish cog wheel? sand clock? launch rocket? -- that will be turned into usual sandclock, spinner, etc icons in front of the workflow names once people are redirected to the workflow page after clicking on the Launch button.

- WRT name, if there is nothing in the URL, just display the usual "workflow". People are used to seeing workflow run names, so I guess they will easily understand what it is about.

- I like parameters presented separately as in the first mock-up. Will make nicer transition to "editable sliders", as it were.

Note: When we shall move from R/O launcher page to R/W launcher page, then we'll have to amend the look of this page anyway, to display some helper texts next to editable boxes etc.  So the connection to "workflow list item design" may be loosened then. I guess we don't have to spend too much time on polishing R/O look if we are going to R/W look in the near future. The above mock-up looks already well enough!
