### ISSUE TITLE
ux: improve list -> details click flow for running workflows

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#240]
When a workflow is composed of several steps and some are done and some are still running, then users see in the workflow list page the "blue" running status signs like:

![w1](https://user-images.githubusercontent.com/517546/158237313-ae4b6946-6bc6-49fa-96f5-d597eed9ee3b.png)

When users click on this workflow to get to the detailed workflow page, they see some "blue" and some "green":

![w2](https://user-images.githubusercontent.com/517546/158237429-57e9284b-f6cc-4d71-838d-e685494a6126.png)

This is essentially because the first step of the workflow is shown by default, and the first step is "done" already.

The UX problem here is that it may be confusing to see "blue" running status on top whilst "green" done status on the bottom, especially if some logs are produced and the page content is otherwise output-heavy. The users may  have a false impression that "finished" concerns the whole workflow, due to the central very visible button position.

We have several solutions how we could improve the user experience here:

(1) If a workflow is running, show the last active "running" step, and not the first "finished" one.  This would give:

![w3](https://user-images.githubusercontent.com/517546/158237901-95746445-39d3-41f2-8349-fec8e65e5bb1.png)

Here things are pretty clear what's happening. The behaviour better answers the original click need that basically asks "show me where this workflow execution is", as it were.

(Similarly to when a workflow failed, we would like to see directly the failed step, not the first one.)

(2) Another solution would be to show Workspace tab by default, instead of the Logs tab. It makes sense to consider making the detailed record page workspace-centric. The produced files are "primary", whilst the logs are sort of "secondary". (Even more so as we don't have live reloading of logs.)

**Comment by mdonadoni** [comment]
The first solution has been implemented in #253
