### ISSUE TITLE
details: harmonise look-and-feel of "refresh" and "hamburger" buttons

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#244]
When a workflow is running, then on the detailed workflow page, when the mouse is far away from the area, one sees:

![r1](https://user-images.githubusercontent.com/517546/158650489-34991cd8-6f97-4181-a5b4-e20be8031d70.png)

When mouse hovers over "refresh" button, one sees it getting darker:

![r2](https://user-images.githubusercontent.com/517546/158650561-8d12e9e4-6e48-472b-924d-62a66331d113.png)

When mouse hovers over "hamburger" button, one sees it getting lighter (and colourful):

![r3](https://user-images.githubusercontent.com/517546/158650735-943dd486-a5db-4ae0-aff8-b76d218f5a65.png)

We should harmonise the style so that when both are "off" they are displayed in the same colour (e.g. dark gray), and when some is "on", it is displayed in another colour (e.g. light grey or light brown).

P.S. Besides cosmetics, using very light grey for "refresh" makes the "refresh" button not to be very visible, which may be a usability problem, because the details page is not auto-refreshing. So we may take the harmonisation occasion to make it nicely visible on pages. Especially useful for Launch-on-REANA functionality.

**Comment by mvidalgarcia** [comment]
> We should harmonise the style so that when both are "off" they are displayed in the same colour (e.g. dark gray), and when some is "on", it is displayed in another colour (e.g. light grey or light brown).

+1 on harmonizing.

All across the UI we have lighter colors when "off" and slightly darker colors on hover, so I would suggest to be consistent with this.

PS. Reminder to also change the kebab menu colors on the workflow list page.
