### ISSUE TITLE
ui: minor, status and running time fo workflow overflows when name is too long

### ISSUE THREAD

**Issue by VMois** [reanahub/reana-ui#245]
![Screenshot 2022-03-17 at 08 50 48](https://user-images.githubusercontent.com/15694232/158762331-4b46e204-5bbb-4be3-b390-8faf3500abb2.png)

Screen resolution: 1920x1200

For testing, you can use the following workflows:

- https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysis/tree/4eb69e073d3b2567c49b2525c2a53341a16dc1ab

- https://github.com/cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysis/tree/v1.3

Launch them with the Launch-on-REANA badge for simplicity.

**Comment by VMois** [comment]
![Screenshot 2022-03-17 at 08 59 21](https://user-images.githubusercontent.com/15694232/158763322-31c98e57-0615-4f27-85c6-9be1c0248c29.png)

**Comment by mvidalgarcia** [comment]
I can't help but think about this.

![image](https://user-images.githubusercontent.com/8863238/158785774-1034415b-798b-412e-ac9e-5243d88ad24d.png)
