### ISSUE TITLE
long workflow name breaks "details" top view

### ISSUE THREAD

**Issue by VMois** [reanahub/reana-ui#249]
For example, when using the launcher, in some cases the workflow name can be very long and break the` details` page layout. The maximum allowed length of workflow name is 255 characters.

![Screenshot 2022-03-21 at 13 38 40](https://user-images.githubusercontent.com/15694232/159265127-dfbcf510-e554-40a3-b3d0-8ce6840fd1da.png)

_Originally posted by @VMois in https://github.com/reanahub/reana-server/issues/464#issuecomment-1073860831_

**Comment by audrium** [comment]
This issue was already reported [here](https://github.com/reanahub/reana-ui/pull/246#issuecomment-1071014998)

**Comment by VMois** [comment]
True. My bad, for some reason I was thinking PR is merged.
