### ISSUE TITLE
profile: more informative quota stats

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#271]
**Current behaviour**

When quota feature is enabled, we are showing quota usage and limits stats in the Your Profile page, such as the following:

![ui-quotas](https://user-images.githubusercontent.com/517546/169256814-76b94572-c608-4921-a06b-df3999b3bcc5.png)

It would be good to additionally guide the user as to what to do next once the quota limits are reached.

**Expected behaviour**

We can display a link to a future documentation page that will mention how to detect workflow runs that consume the most space, how to delete unnecessary workflow runs, and how to set shorter retention periods for temporary data.

This issue is a Web UI counterpart to its CLI UI sister described in https://github.com/reanahub/reana-client/issues/607

**Comment by audrium** [comment]
Closing since it was implemented in [this PR](https://github.com/reanahub/reana-ui/pull/275)
