### ISSUE TITLE
ui: expose job duration times on detailed workflow pages

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#286]
**Current behaviour**

Currently, the REANA web interface exposes only the total runtime of a workflow:

![exposed-times](https://user-images.githubusercontent.com/517546/176448350-5bd75334-dd54-4651-ace8-ea296eb24c8b.png)

We don't expose times for individual jobs on the web UI, only on CLI:

```console
$ reana-client logs -w dimuon
...
==> Step: compile
==> Status: finished
==> Started: 2022-06-21T09:41:34
==> Finished: 2022-06-21T09:42:58
...
==> Step: run
==> Status: finished
==> Started: 2022-06-21T09:42:58
==> Finished: 2022-06-21T09:44:20
```

It would be useful to expose job runtime durations in the Web UI as well.

**Expected behaviour**

Let's amend the web interface detailed record page to expose job duration times at some convenient location on the page:

![exposed-times-wish](https://user-images.githubusercontent.com/517546/176448426-a21363a4-bec4-4671-a3f5-3e52ce0a0f65.png)

Possible options:

- For example, the dropdown could read "compile (30 sec)" instead of only "compile".

- For example, the green button "Finished" could read "Finished in 30 seconds".

- For example, we can enrich salmon text area body to show the duration time of a step at the very bottom.

- For example, we can display duration times elsewhere on the page.

The goal of this issue is (i) to propose how to best expose job duration times in the web UI in a user-friendly way, and then (ii) to  implement the exposure.

**Comment by tiborsimko** [comment]
Another, more complete example would be to introduce a new tab "Statistics" where we would expose a graph about workflow and job times, and perhaps later other metric information such as memory consumption.  (A bit similar to Snakemake reports actually.)

An ASCII art example:

```
> Logs    > Workspace   > Specification   -> Statistics

job a   12:10 [----] 10min 
job b   12:21 [-------------------------------------------] 50min
job c   12:22 [-------------------------------------]  45 min
job d   13:30 [--------]   13 min
job e   13:45 [-------------------]  25 min
```

We could order the output either by the job name or running time, we could display also real time map, and the job names could link to job log output, etc.  (Actually this could be not in a new tab, but part of the logs tab, as another option.)

Just to mention a few options for design musings...

**Comment by mdonadoni** [comment]
> For example, the dropdown could read "compile (30 sec)" instead of only "compile".

This can be problematic when the job names are very long, as we would either need to make the dropdown bigger or we would need to shorten the job name even more.

> For example, we can enrich salmon text area body to show the duration time of a step at the very bottom.

I think that it is better if we keep the information about the job clearly separated from the logs, as otherwise it might become difficult to find a given piece of information if all of them are in plain text and mixed with the logs.

> For example, the green button "Finished" could read "Finished in 30 seconds".

#290 implements this option, as I think it is the best one. If it is good, we can proceed with this and we can then discuss about having a dedicated statistics tab later.

What do you all think?

**Comment by audrium** [comment]
> https://github.com/reanahub/reana-ui/pull/290 implements this option, as I think it is the best one. If it is good, we can proceed with this and we can then discuss about having a dedicated statistics tab later.

I also think that this is the best option and agree that as a first step we could introduce it into the `logs` tab, before creating a new statistics tab!
