### ISSUE TITLE
ui: improve approximate time announcements in retention messages

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#291]
**Current behaviour**

When someone configures a retention period of 10 days, and inspects the workflow that freshly finished, the web UI shows:

![retention-week](https://user-images.githubusercontent.com/517546/184303305-8ce1c01d-7cd8-407a-8de7-941e060f872e.png)

This seems to send a contradictory message about when the files will be deleted: in 10 days? or in a week? This may be confusing especially since the workflow run has just freshly terminated.  

Note that we do show exact time to users, if they hover over "in a week", they would see the exact time being indicated. However, the phrase "In a week" looks formatted just like an ordinary text, not something users would expect to go and hover over. So I think majority won't notice.

Hence the feeling of "apparent contradiction".

**Expected behaviour**

For matters as important as removing workflow files, we should be more precise here. We have two possible directions:

1. **Softening the language.** Since our time display library shows "approximate verbiage" for date time points, we can soften the estimation and print "in about a week" instead of "In a week".

2. **Using more exact times.** Instead of "In a week", we can print more exact timing,  such as "After 2022-08-22 23:59". Note that I'm keeping an element of uncertainty here by means of the word "after", since our retention deletion daemon is not guaranteed to run at an exact hour or minute. Also, we could retain hover, and print "in a week" when hovering.  (This would be basically inverting current normal text <-> hover text display.)

3. **Combining the two instead of hover.** We can combine estimate and exact into one phrase, and display something like "2022-08-22 23:59 (in a week)" which would solve the "undiscoverable hover" UX problem mentioned above.

In my eyes, the file deletion is quite an important event, so I would tend to displaying exact timings first and approximate verbiage later; and since the text is printed in a normal font, I'd probably vote for 3 removing hover.

**Comment by mdonadoni** [comment]
> This seems to send a contradictory message about when the files will be deleted: in 10 days? or in a week? This may be confusing especially since the workflow run has just freshly terminated.

The idea was to give a rough but conservative estimate of the the time before the deletion of the files. It was even worse before, as by default the library we use can round the durations up, so it could happen that files would be deleted before the deadline displayed in the UI. However, I agree that the current way can also be somewhat confusing.

> In my eyes, the file deletion is quite an important event, so I would tend to displaying exact timings first and approximate verbiage later; and since the text is printed in a normal font, I'd probably vote for 3 removing hover.

I also prefer the third option!
