### ISSUE TITLE
login: add next_url param to login url

### ISSUE THREAD

**Issue by leticiawanderley** [reanahub/reana-ui#35]
The [CERN oauth login url](https://github.com/leticiawanderley/reana-ui/blob/ui-update-login-url/reana-ui/src/pages/login/components/LoginForm.js#L26) should have a `next_url` parameter to make CERN SSO redirect the user back to REANA.

**Comment by diegodelemos** [comment]
Working already in latest master, [handled by Invenio-OAuthclient](https://github.com/inveniosoftware/invenio-oauthclient/blob/ca0e40e6483d2f8fe8ccda670c56bc6423bb69b0/invenio_oauthclient/handlers.py#L345).
