### ISSUE TITLE
login: show UI depending of user being logged in or not

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-ui#36]
Whether the user is logged in or not should be part of the state of the React application. Currently, we just add links to the pages, for example to [`my GitLab projects`](https://github.com/reanahub/reana-ui/blob/12e92dd45ea067eff0bb844b79674fc72a33e6ad/reana-ui/src/pages/login/components/LoginForm.js#L47), so regardless of the user being logged in or not the link is there and they can navigate (of course the REST calls behind the scenes will fail because there is no session cookie) which is confusing.

User interface state should show according to the user status, logged in, anonymous etc..

**Comment by mvidalgarcia** [comment]
Would anonymous be a valid user status? i.e. could an anonymous user access other pages than the login page?

**Comment by diegodelemos** [comment]
Not for now, only logged-in users are able to manage workflows. But this could be a feature in the near future, so anybody can try a [REANA example](https://github.com/reanahub?utf8=%E2%9C%93&q=demo&type=&language=) live (kind of an example gallery) and track its progress.
