### ISSUE TITLE
Bug in badge creator url

### ISSUE THREAD

**Issue by e-sacchi** [reanahub/reana-ui#388]
In the badge creator page (https://reana-p4n.aip.de/launcher-badge) the output Markdown code for the badge contains an extra "$" in the URL which prevents the badge to be clickable.

**Comment by e-sacchi** [comment]
One extra dollar is still there (in the box containing the output  Markdown code to copy for creating the badge (see screenshot below).  

<img width="692" alt="Screenshot 2024-01-25 at 10 51 23" src="https://github.com/reanahub/reana-ui/assets/77434762/17ea898c-86aa-4a5d-9ebd-f74757b1379e">

**Comment by mdonadoni** [comment]
Hello @e-sacchi ,

I have checked the new changes from https://github.com/reanahub/reana-ui/pull/389 in a local instance, and it seems like the Markdown code snippet is now correct.

![](https://github.com/reanahub/reana-ui/assets/13397702/76e51963-21c4-4020-93c0-370290e302bf)

Note that these changes are not part of any release (yet), so unless you are running the latest development version of REANA locally, you will not see these changes until the instance you are using will be updated to a (future) release containing this fix.

Please let us know if you have more issues and feel free to reopen the issue if the issue persists!

**Comment by e-sacchi** [comment]
I understand, thanks!
