### ISSUE TITLE
RFC UI component framework

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#4]
Compare UI component frameworks for https://reactjs.org/ and select one. 

For example:

- http://grommet.io/ 

which is already being used in the CERN Analysis Preservation service. CC @annatrz @ioannistsanaktsidis @pamfilos

Other possible candidates:

- https://ant.design/
- https://material-ui.com/
- https://react.semantic-ui.com/

which are being tried out in other Invenio and Indico based services. CC @lnielsen @ludmilamarian  @pferreir

**Comment by Sinclert** [comment]
I have been doing some research on [Grommet](http://grommet.io/), [Material-UI](https://material-ui.com/) and [Semantic-ui](https://react.semantic-ui.com/); as well as some mock ups with the first 2 frameworks. There are some peculiarities to consider:

| Concept       | Grommet          | Material-UI  | Semantic-UI  |
| ------------- |:-------------:| -----:|-----:|
| `Button-disable`      | No | Yes | Yes |
| `ProgressBar-labels`      | Yes | No | Yes |
| `ProgressBar-colors` | Yes | No | Yes |
| `NodesGraph` | Yes | No | No |
| `Table-Pagination` | No | Yes | Yes |
| `Progress-CircleShape` | Yes | Yes | No |
| Documentation quality | Medium | Medium | Good |

My personal opinion is to go either for Grommet or for Semantic-UI.

**Comment by diegodelemos** [comment]
Taking into account all mock-ups and the comparison matrix I would go for Semantic-UI since it looks more mature (documentation, community..) and highly customizable.

**Comment by Sinclert** [comment]
I think so too. We could also combine it with another framework just to get the Circular Progress component in case we need it
