### ISSUE TITLE
TypeError: t.loginProviderConfig is undefined

### ISSUE THREAD

**Issue by cfelder** [reanahub/reana-ui#407]
Hi,

I am currently deploying to a OpenShift/Okd 4 instance.
The ``ui-config.yaml`` in ConfigMap ``reana-config`` contains:

```
login_provider_config: []
```

Nevertheless I get the following stacktrace.

```
GET
https://reana.dev.ocp.example.com/signin
[HTTP/1.1 304 Not Modified 20183ms]

GET
https://reana.dev.ocp.example.com/static/js/main.fbfee2f8.js
[HTTP/1.1 200 OK 0ms]

GET
https://fonts.gstatic.com/s/opensans/v40/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS-mu0SC55I.woff2
[HTTP/2 200  0ms]

TypeError: t.loginProviderConfig is undefined
    dl Signin.js:73
    React 13
    notify Redux
    uc React
    Redux 6
    <anonymous> actions.js:123
    promise callback* actions.js:123
    D Redux
    <anonymous> index.js:21
    <anonymous> index.js:24
    <anonymous> index.js:31
    <anonymous> index.js:31
react-dom.production.min.js:189:29
GET
https://reana.dev.ocp.example.com/favicon.ico
[HTTP/1.1 200 OK 0ms]

Uncaught TypeError: t.loginProviderConfig is undefined
    dl Signin.js:73
    React 13
    notify Redux
    uc React
    Redux 6
    <anonymous> actions.js:123
    promise callback* actions.js:123
    D Redux
    <anonymous> index.js:21
    <anonymous> index.js:24
    <anonymous> index.js:31
    <anonymous> index.js:31
Signin.js:73:9
    dl Signin.js:73
    React 13
    notify Redux
    uc React
    Redux 6
    <anonymous> actions.js:123
    (Async: promise callback)
    <anonymous> actions.js:123
    D Redux
    <anonymous> index.js:21
    <anonymous> index.js:24
    <anonymous> index.js:31
    <anonymous> index.js:31
```

Any help would be appreciated.

Best
Christian

**Comment by mdonadoni** [comment]
Hello @cfelder ,

What version of REANA are you using?

The web UI should make a request to `/api/config` when it is accessed, could you copy-paste the reply here?

**Comment by cfelder** [comment]
Thanks for pointing me into the right direction.

I've just put the ingress on the ``nginx`` based ``reana-ui`` container. I've to configure the ingress manually using OpenShift's Route CRD besides what is provided in the helm charts. I've now added another route to the ``/api`` endpoint and the login dialog is shown. I'll add all necessary routes now.

I am currently using github.com:reanahub/reana v0.6.1-410-g44dde34 (current master)

This issue can be closed. Thanks!

**Comment by mdonadoni** [comment]
> I've just put the ingress on the `nginx` based `reana-ui` container. I've to configure the ingress manually using OpenShift's Route CRD besides what is provided in the helm charts. I've now added another route to the `/api` endpoint and the login dialog is shown. I'll add all necessary routes now.


No problem!

This might be helpful, as it list all the routes needed: https://docs.reana.io/administration/configuration/configuring-cluster-ingress/#setting-up-manual-ingresses
