### ISSUE TITLE
mock: login page

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#5]
Create mock-up pages for basic user login, registration, email verification, notification settings, API token generation.

Here is a simple example: 

![img_20180706_155147](https://user-images.githubusercontent.com/517546/42382733-81602530-8135-11e8-90e3-35dde05a3942.jpg)

**Comment by tiborsimko** [comment]
@Sinclert @diegodelemos Perhaps try out various UI component options with https://github.com/storybooks/storybook?

**Comment by Sinclert** [comment]
Maybe we could remove the header in this page? The logo could be on top of the login form. That way the interface would be cleaner
