### ISSUE TITLE
react: replace deprecated componentWillMount and componentWillReceiveProps

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-ui#51]
Replace deprecated [`componentWillMount`](https://reactjs.org/docs/react-component.html#unsafe_componentwillmount) and [`componentWillReceiveProps`](https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops).

Warnings are displayed in the console because of this.
Ideally we should replace them in favor of [react hook's lifecycle](https://reactjs.org/docs/hooks-intro.html)

**Comment by laumair** [comment]
@mvidalgarcia Doesn't look like the latest [master](2e6ccbcc8c4c7ff8e0e0879072ecf7da8a8913a2) has any instances of `componentWillMount` or `componentWillReceiveProps`.

**Comment by mvidalgarcia** [comment]
> @mvidalgarcia Doesn't look like the latest [master](2e6ccbcc8c4c7ff8e0e0879072ecf7da8a8913a2) has any instances of `componentWillMount` or `componentWillReceiveProps`.

You're right, thanks so much! 👍 
With the last refactor of the UI last February, we got rid of all the classes and now the code is 100% hooks oriented.
