### ISSUE TITLE
ui: create mock-ups to come up with final user flow

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-ui#58]
Currently, REANA UI only shows the user token. However, we have other pages which are just hidden. We should come up with a set of mock-ups and how they should be browsed.

Once the mock-ups and user flow is defined, re-style the UI uniformly.

**Comment by mvidalgarcia** [comment]
Mockups: [REANA-UI.pdf](https://github.com/reanahub/reana-ui/files/4117504/REANA-UI.pdf)

**Comment by lukasheinrich** [comment]
would be nice if we could keep in mind non-linear workflows (yadage / cwl) in mind when designinig the mockups since probably this will inform some of the choices. A good testcase probably is the BSM workflow

**Comment by tiborsimko** [comment]
@lukasheinrich Definitely, the DAG visualisation is something that will come after the workshop.

**Comment by mvidalgarcia** [comment]
New version incorporating a _real_ Htt example and applying some feedback: [REANA-UI.pdf](https://github.com/reanahub/reana-ui/files/4134929/REANA-UI.pdf)

**Comment by diegodelemos** [comment]
Mock-ups done!
