### ISSUE TITLE
ui: no workflows page

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-ui#63]
![image](https://user-images.githubusercontent.com/8863238/73546646-de360f00-443d-11ea-831c-8c68ce2a4780.png)

**Comment by tiborsimko** [comment]
A generally white background page, with sepia used for code text area and other box inserts, could be a 
nice general style that is reusable everywhere, e.g. here on the welcome page, on user settings page, on the big workflow details page, etc.

**Comment by mvidalgarcia** [comment]
> A generally white background page, with sepia used for code text area and other box inserts, could be a
> nice general style that is reusable everywhere, e.g. here on the welcome page, on user settings page, on the big workflow details page, etc.

@tiborsimko Do you mean something like this?
![image](https://user-images.githubusercontent.com/8863238/73829310-09847980-4803-11ea-80f7-2e10eb7262a8.png)

cc/ @roksys @diegodelemos it'd be nice if you could express your opinion.

**Comment by diegodelemos** [comment]
In my eyes, with the outer box surrounding everything (original mock-up) looks better.

**Comment by mvidalgarcia** [comment]
Welcome page changed.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/8863238/73869220-360fb400-484a-11ea-8f3d-679648e49323.png">

PS. IMHO I also prefer the original version.

**Comment by tiborsimko** [comment]
- If you look at the ensemble of all the pages, it makes sense if all console snippets -- the code example scenarios in docs pages, the logs output in the live workflow details page, the REANA_ACCESS_TOKEN exports in user settings page, etc -- it may be beneficial if they all look alike.  Allows to quickly identify "console stuff" visually across the site.  This is why I thought about using sepia for all of them... Inverted graphics may be nicer in isolation for some of the pages, but if we can invent the same theme applying for all pages, I think it is advantageous overall for the end user.

- Note that page title may be better said "Welcome to REANA!" and the phrase "It seems that .... for the first time."  (with dot) be better moved as the first sentence of the text body. 

- (Hmm, perhaps the "limited width" is also what made you prefer boxed version?  OTOH, user settings page also have "limited width", so this is perhaps something to consider later when we shall have more pages?)
