### ISSUE TITLE
mock: workflow list

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#7]
Create a mock-up page which will list of all user workflows and show their status overview at a glance. It should show the most important information about each workflow run with a possibility to click to a separate workflow run page to see view more. The list fields should be sortable and/or searchable. The most important actions such as see the last logs, delete a run, restart a run could be offered last in the form of a drop-down menu or graphical icons.

Here is one possible example:

![img_20180706_155211](https://user-images.githubusercontent.com/517546/42383042-608be582-8136-11e8-8e5d-749718378ebe.jpg)

**Comment by Sinclert** [comment]
I have done a first mockup using [StoryBooks](https://storybook.js.org) and the [Grommet](http://grommet.io/) UI framewok.

While implementing the framework, I have discovered the following particularities:
1. The buttons has not `disable` property, so the only way to disable them is to specify a lighter color and consider it on the `onClick` function. This will be solved in the next release of Grommet. Source: https://github.com/grommet/grommet/issues/1681
2. There is no pagination, and apparently is something they are not considering. Source: https://github.com/grommet/grommet/issues/262

![screen shot 2018-07-10 at 15 43 27](https://user-images.githubusercontent.com/6978377/42514324-6f20fa30-8459-11e8-8647-2aaac6f05c41.png)

**Comment by Sinclert** [comment]
Second mockup, this time using [Material-UI](https://material-ui.com).

While using the framework, I have discovered the following particuliarities:
1. The `LinearProgress` component is very limited, apparently it only accept 2 colours (primary and secondary). Additionally, there is no obvious way to add labels (such as how many steps remaining...). 
2. Pagination and sorting can be implemented, but they are not included by default in the component. They must be added later.
3. The framework does not have any kind of `Header` or `Footer` native components, as there is in Grommet.

![screen shot 2018-07-11 at 13 28 37](https://user-images.githubusercontent.com/6978377/42568946-253a9d98-850f-11e8-89f4-ac762ea7caad.png)

**Comment by tiborsimko** [comment]
@Sinclert Great mockups :+1:  Very useful to compare different frameworks under consideration. 

Some quick comments:

- WRT Grommet and pagination, interesting choice... I guess we might need it since the number of user workflow runs may be potentially large.  Dunno about infinite scroll there. Anyway we may even need to consider server-side pagination.

- WRT missing components, we can consider an option to combine more frameworks together if need be, e.g. I understood from @pferreir that Indico uses Semantic-UI-React for most thinkgs but that it also borrows some components from Ant-Design for advanced date/time pickers, since Semantic-UI-React did not have anything directly useful there. (referring to #4)

**Comment by Sinclert** [comment]
Thanks! I forgot to mention about tabs. I thought about the posibility of distinguish between finished jobs, and current running jobs using [Grommet tabs](http://grommet.io/docs/tabs)

**Comment by Sinclert** [comment]
Third mockup, this time using [Semantic-UI](https://react.semantic-ui.com/introduction).

While using the framework, I have discovered the following particuliarities:

1. The buttons / icons have a `disable` option.
2. The `Progress` component is very complete. Labels could be indicated inside, or below the progress bar, and there are freedom to apply any color **within** the ones they provide. Additionally, the progress bar could be 'animated' to show progress.
3. Pagination and sorting can be implemented. The sorting function is provided in the examples :)
<img width="1032" alt="screen shot 2018-07-17 at 09 29 48" src="https://user-images.githubusercontent.com/6978377/42802801-434dd266-89a4-11e8-83d1-a93d4d29dddd.png">

**Comment by Sinclert** [comment]
Closing. The implementation has been started.
