### ISSUE TITLE
sessions: easy way to open, list and close interactive sessions

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#77]
The "Your workflows" UI now lists conveniently batch workflows that a user has run.

Users can open and close interactive sessions such as Jupyter notebooks on the workflow workspace using the `open`, `list --sessions` and `close` commands.

We should amend UI to allow opening, inspecting and closing interactive sessions from the UI as well.

It could be a independent feature ("Your interactive sessions" akin no workflow list page), or linked closely to the workflow (new tab "Interactive sesions" or some such on the workflow detail page).

Let's explore this via mock-ups before implementation starts.

**Comment by tiborsimko** [comment]
Let's start by designing UI mock-ups.

The current constraint is that users can open only one session on a given workflow workspace. So the approach (b) mentioned above would do (i.e. notebook tab on the workflow detailed page, plus a notebook logo on the workflow list page). We could e.g. use here the new hamburger menu which would offer "Open Jupyter notebook" for the given workflow run.

If we relax this constraint, and if users can have several interactive sessions opened for the same workflow run (e.g. jupyter notebook, e.g. zeppelin, e.g. exec shell), then we'd probably need to look for the approach (a) to have a new endpoint listing all your sessions.

There were also use cases of people asking to simply open a notebook without having any associated workflow run; this would again call for approach (a), the home page offering possibility to open a notebook without having any workflow. However, this would be going a bit too much beyond MVP.... Our primary focus is on running workflows, and only then on possibly opening notebooks on their workspaces.

So I guess for MVP it would be OK to look at the (b) approach.

**Comment by audrium** [comment]
Here is how MVP workflow list page could look like:
![mvp_w_list](https://user-images.githubusercontent.com/4990025/94807811-77b02900-03f0-11eb-9d57-0cfffd0d697d.png)

Do we want to also display a notebook logo if a user has an open session for some workflows in this page? I've added the most similar icon which I could find to `root6-roofit` workspace to illustrate this case

**Comment by tiborsimko** [comment]
> Do we want to also display a notebook logo if a user has an open session for some workflows in this page? 

That would be good; we could even make the icon clickable so that the notebook URL would be opened in another tab.

> MVP workflow details page

Seeing the tab mock-up, it seems a bit too prominent... The thing is that opening a notebook is rather an exceptional thing; it will most often be just empty. And, for now, we only have one notebook per workflow.  So it could be simply a button "Open Jupyter notebook" (or some kind of another hamburger menu on the detailed page). Especially if we keep one-workflow-one-notebook rule for the time being... Let's see about possibly expanding it after we amend the data model.

**Comment by audrium** [comment]
Second iteration of MVP workflow details page:
![mvp-w-details-v2](https://user-images.githubusercontent.com/4990025/94816040-87813a80-03fb-11eb-9a65-0a52d58bd260.png)
I've added a hamburger button with the same two options from the workflow list page

**Comment by mvidalgarcia** [comment]
👍 to the idea of notebook icon pointing to the notebook URL. It would be amazing if we could display several statuses (opening, ready) using diferent colors/icons, but I guess we will have to wait for WebSockets for that.
