### ISSUE TITLE
mock: workflow page

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#8]
Create mock-up page that would show all the details about some concrete workflow run.  This page would be the main thing that the users will interact with after coming here either from the welcome dashboard or from the full workflow list. The users may leave this page opened in a tab to see the progress live, to check the logs, etc.  (Note that inputs may be variables with values or input code files or input data files. The layout could serve for future rerunning of workflows with modified inputs.)  

Here is one possible example:

![img_20180706_155219](https://user-images.githubusercontent.com/517546/42383321-2eb5dfa8-8137-11e8-8bcc-d7d95882fce5.jpg)

**Comment by lukasheinrich** [comment]
great to see a UI coming together. Would be interesting to hash out what "interactive" workflows should look like. In my prototype, I was thinking, perhaps the workflow engine would expose a OpenAPI specified REST API with which the user can interact with a "live" workflow:

e.g. 

non-interactive workflow: a kubernetes `Job` API object that just runs the engine to completion
interactive workflow: a kubernetes `Deployment` API object that exposes the API

users could then interact with the workflow using

a) the workflow page, which presents a (perhaps engine-specific) UI that translates to API calls against the engine
b) the reana client from the command line
c) a notebook with a python client? ..

**Comment by Sinclert** [comment]
Closed due to #22
