### ISSUE TITLE
ui: user token creation through request/approval process

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-ui#93]
### ui

- [x] Create some fast mockups to discuss before starting with the actual implementation.
- [x] Prevent displaying the user token in the welcome page for social logged in users. Instead, display some message saying that social login requires verification and the token is in a "waiting" state and that administrator will contact him/her back once it's approved.
- [x] Show waiting/approved status in profile page
- [x] Handle 'revoked' case

### server
- [x] Create a new endpoint to be called from the ui to create a user token and mark it as `requested`.
  1. Use [`User.request_access_token()`](https://github.com/reanahub/reana-db/blob/master/reana_db/models.py#L102-L115)
  2. Send email to reana administrators

Tightly related to https://github.com/reanahub/reana-server/issues/235

**Comment by tiborsimko** [comment]
Ad 2, we can do it for everybody, not only for social logins.

The message would go like:

```
Welcome to REANA!

It seems that this is your first login to REANA. In order to use the system,
you need to ask for an access token.

      [ Request token ]
```

After people click on the "Request token" button, we can show something like:


```
Welcome to REANA!

Your access token request has been forwarded to REANA administrators.

Action: requested access token
Date: YYYY-MM-DD HH:MM:SS
Status: pending
```

After admins approve the person, we can display the usual message:

```
Welcome to REANA!

Your access token is aaabbb111333.

It seems that you have not run any workflows yet.  Would you like 
to run a first reproducible analysis example? Please proceed
as follows:

    $ ssh lxplus 
    ...
    $ git clone
    ...
    $ reana-client run
    ...
```

P.S. For people using REANA from outside of CERN, we'd also have to point to
`pip install` example, not only to `ssh lxplus` example, on how to get the
`reana-client` CLI executable.

**Comment by mvidalgarcia** [comment]
Some mockups:

Before requesting token:
![image](https://user-images.githubusercontent.com/8863238/79956636-b379b680-8480-11ea-8bbd-c9d786798f1b.png)

After requesting token:
![image](https://user-images.githubusercontent.com/8863238/79956683-c3919600-8480-11ea-9fcd-5a39d38c1ad9.png)
