### ISSUE TITLE
ui: better error pages

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-ui#99]
Introduce better error pages for different HTTP status responses.
For now a tiny component `<Error />` was introduced. It permits to customize title and message.
![image](https://user-images.githubusercontent.com/8863238/82815378-56b35680-9e99-11ea-840e-be8f2361dc30.png)

A [good place](https://www.google.com/search?q=error+pages+ui) for inspiration.

**Comment by mvidalgarcia** [comment]
Evaluate if a sign out link in these pages makes sense. At the moment a revoked user cannot sign out and try to sign in with a different account.

**Comment by audrium** [comment]
We should also think about unifying the error handling across the application. Some disscusion happened in this PR: https://github.com/reanahub/reana-ui/pull/120#discussion_r487907511 with a suggestion to use a similar approach to one described [here](https://alexandrempsantos.com/sane-error-handling-react-redux/#after---how-to-solve-these-problems).

**Comment by mvidalgarcia** [comment]
When accessing `reana.cern.ch/foo`, one gets a blank page. No errors HTTP occur involved as this is not foreseen.

![image](https://user-images.githubusercontent.com/8863238/100134751-fa051880-2e88-11eb-974f-9173833b8fa2.png)

We should redirect to an error page. This can be done [via React routes](https://github.com/reanahub/reana-ui/blob/28ec51bdd26705fd0cf3b3ec5efc4a22cdeace87/reana-ui/src/components/App.js#L53-L73). We probably need a new `Route` that matches all (`*`?) and is evaluated the last one, to redirect to a 404 page.
